# Generated by Django 5.2.4 on 2025-07-31 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=100, unique=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pemasok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemasok', models.CharField(max_length=200)),
                ('kontak_person', models.CharField(blank=True, max_length=100, null=True)),
                ('nomor_telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pemasok',
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(help_text='Contoh: Indomie Goreng, Gula Pasir Curah', max_length=200, unique=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produk', to='products.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='VarianProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_varian', models.CharField(max_length=100)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('stok', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('satuan', models.CharField(choices=[('pcs', 'Pcs'), ('kg', 'Kg'), ('gram', 'Gram'), ('liter', 'Liter'), ('bungkus', 'Bungkus'), ('sachet', 'Sachet')], max_length=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('peringatan_stok_rendah', models.DecimalField(decimal_places=3, default=10.0, max_digits=10)),
                ('harga_jual_normal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('harga_jual_reseller', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_favorit', models.BooleanField(default=False)),
                ('pemasok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='varian_produk', to='products.pemasok')),
                ('produk_induk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varian', to='products.produk')),
            ],
        ),
        migrations.CreateModel(
            name='AturanHargaKuantitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_minimal', models.PositiveIntegerField()),
                ('harga_total_khusus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('varian_produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aturan_harga', to='products.varianproduk')),
            ],
            options={
                'verbose_name_plural': 'Aturan Harga Kuantitas',
                'unique_together': {('varian_produk', 'jumlah_minimal')},
            },
        ),
    ]
