# Generated by Django 5.2.4 on 2025-07-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='varianproduk',
            name='lacak_stok',
            field=models.BooleanField(default=True),
        ),
    ]
