# Generated by Django 5.2.4 on 2025-08-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_varianproduk_lacak_stok'),
    ]

    operations = [
        migrations.AddField(
            model_name='varianproduk',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Nonaktifkan untuk menyembunyikan dari daftar jual'),
        ),
    ]
