# Generated by Django 5.2.4 on 2025-09-13 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_varianproduk_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='varianproduk',
            options={'verbose_name_plural': 'Varian Produk'},
        ),
        migrations.AlterUniqueTogether(
            name='varianproduk',
            unique_together={('produk_induk', 'nama_varian')},
        ),
    ]
