# Generated by Django 5.2.4 on 2025-07-31 07:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(max_length=255)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HutangPiutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('HUTANG', 'Hutang Dagang'), ('PIUTANG', 'Piutang Dagang')], max_length=10)),
                ('pelanggan_nama', models.CharField(blank=True, max_length=150, null=True)),
                ('total_awal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lunas', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tanggal_jatuh_tempo', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_bayar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanggal_bayar', models.DateTimeField(auto_now_add=True)),
                ('catatan', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.DecimalField(decimal_places=3, help_text='Positif untuk stok masuk, negatif untuk stok keluar', max_digits=10)),
                ('stock_after', models.DecimalField(decimal_places=3, default=0, help_text='Jumlah stok setelah perubahan', max_digits=10)),
                ('reason', models.CharField(choices=[('PEMBELIAN', 'Pembelian dari Supplier'), ('AWAL', 'Stok Awal'), ('RETUR', 'Retur Pelanggan'), ('RUSAK', 'Barang Rusak/Kadaluwarsa'), ('HILANG', 'Barang Hilang'), ('INTERNAL', 'Keperluan Toko'), ('OPNAME', 'Penyesuaian Opname'), ('PENJUALAN', 'Penjualan Kasir')], default='PEMBELIAN', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_toko', models.CharField(default='Toko Bu Ning', max_length=100)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('footer_struk', models.CharField(default='Terima Kasih Telah Berbelanja!', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_transaksi', models.CharField(editable=False, max_length=50, unique=True)),
                ('total_harga', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('diskon_nominal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_setelah_diskon', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jumlah_bayar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kembalian', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metode_pembayaran', models.CharField(choices=[('Tunai', 'Tunai'), ('QRIS', 'QRIS'), ('Debit', 'Debit')], default='Tunai', max_length=20)),
                ('status', models.CharField(choices=[('Selesai', 'Selesai'), ('Dibatalkan', 'Dibatalkan'), ('Ditahan', 'Ditahan')], default='Selesai', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Transaksi',
            },
        ),
        migrations.CreateModel(
            name='DetailTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=3, max_digits=10)),
                ('harga_saat_transaksi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('varian_produk_terjual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.varianproduk')),
            ],
            options={
                'verbose_name_plural': 'Detail Transaksi',
            },
        ),
    ]
