# Generated by Django 5.2.4 on 2025-08-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_pelanggan_riwayatsimpanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='customer_type',
            field=models.CharField(choices=[('Biasa', 'Biasa'), ('Reseller', 'Reseller')], default='Biasa', max_length=10),
        ),
    ]
