# Generated by Django 5.2.4 on 2025-08-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaksi_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='notes',
            field=models.CharField(blank=True, help_text='Catatan atau nama untuk transaksi yang ditahan', max_length=100, null=True),
        ),
    ]
