# Generated by Django 5.2.4 on 2025-12-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('kasir', 'Kasir'), ('guest', 'Guest')], default='kasir', help_text='Peran pengguna dalam sistem', max_length=10),
        ),
    ]
